#TownyPay
#Made by Tomhmagic for TanukiCraft
#Check out our server running towny at play.tanukicraft.net
#https://discord.gg/zd7pvJY9Zr


#--------------------------------------------#
#              Town Settings                 #
#--------------------------------------------#

TownSettings:
  #Profit setting for towns, profit is worked out as
  #(Current balance - (ProfitCalc * upkeep))
  Profit:
    Multiplier: 2.0

  MayorPay:
    #Enable Mayor Pay, Disable if you just want the budget system
    Enabled: true
    #If true, Mayors can toggle their pay on or off
    CanToggle: false
    #If true, allow the Mayor to set their pay, uses Budget.Min and Budget.Max to give an allowed range
    CanSet: true
    #If true, Pay and Tax would be a fixed amount, not percentage
    PayFixedAmount: false
    #Value is percentage of profit paid to mayor or fixed amount if PayFixedAmount=true, Min and Max only needed if CanSet=true
    Pay:
      Value: 20
      Min: 5
      Max: 30
    #Percentage of tax to take from the pay, if FixedAmount=true then tax is fixed amount and cannot be higher than Pay.Value
    Tax: 20.0
    #Minimum balance before the system will pay a Mayor, if using FixedAmount, set this no less than Pay.Value
    #if FixedAmount is false, then it will use the profit to calculate Mayors pay
    MinimumBal: 0.0

  BudgetSettings:
    #If true, Budget would be a fixed amount
    FixedBudget: false
    #Percentage of profit, fixed amount if FixedBudget=true
    Budget: 10.0
    #If FixedBudget false, set an amount for a minimum balance for the percentage calculations to return a budget.
    #Must be higher than 0.0
    MinimumBal: 1.0

    #Tax percentage to be taken from the payee
    Tax:
      #How much tax to take from paying a resident in the same town
      Resident: 10.0
      #How much tax to take from paying a resident not in the same town
      Outsider: 20.0


#--------------------------------------------#
#             Nation Settings                #
#--------------------------------------------#

NationSettings:
  #Profit setting for nations, profit is worked out as
  #(Current balance - (ProfitCalc * upkeep))
  Profit:
    Multiplier: 2.0


  KingPay:
    #Enable King Pay, Disable if you just want the budget system
    Enabled: true
    #If true, Mayors can toggle their pay on or off
    CanToggle: false
    #If true, allow the King to set their pay, uses Budget.Min and Budget.Max to give an allowed range
    CanSet: true
    #If true, Pay and Tax would be a fixed amount, not percentage
    PayFixedAmount: false
    #Value is percentage of profit paid to king or fixed amount if PayFixedAmount=true, Min and Max only needed if CanSet=true
    Pay:
      Value: 20
      Min: 5
      Max: 30
    #Percentage of tax to take from the pay, if FixedAmount=true then tax is fixed amount and cannot be higher than Pay.Value
    Tax: 20.0
    #Minimum balance before the system will pay a King, if using FixedAmount, set this no less than Pay.Value
    #if FixedAmount is false, then it will use the profit to calculate Kings pay
    MinimumBal: 0.0

  BudgetSettings:
    #If true, Budget would be a fixed amount
    FixedBudget: false
    #Percentage of profit, fixed amount if FixedBudget=true
    Budget: 10.0
    #If FixedBudget false, set an amount for a minimum balance for the percentage calculations to return a budget.
    #Must be higher than 0.0
    MinimumBal: 1.0

    #Tax percentage to be taken from the payee
    Tax:
      #How much tax to take from paying a resident in the same nation
      Resident: 10.0
      #How much tax to take from paying a resident not in the same nation
      Outsider: 20.0

#--------------------------------------------#
#            Resident Settings               #
#--------------------------------------------#
ResidentSettings:
  #Tax percentage to be taken from the payee
  Tax:
    #How much tax to take from paying a resident in the same town or nation
    Resident: 10.0
    #How much tax to take from paying a resident not in the same town or nation
    Outsider: 20.0
